DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS icons CASCADE;
DROP TABLE IF EXISTS favorites CASCADE;
DROP TABLE IF EXISTS markers_info CASCADE;
DROP TABLE IF EXISTS markers CASCADE;
DROP TABLE IF EXISTS maps CASCADE;

CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  email VARCHAR(255) NOT NULL
);

CREATE TABLE icons (
  id SERIAL PRIMARY KEY NOT NULL,
  icon_name VARCHAR(255) NOT NULL,
  img_src VARCHAR(255) NOT NULL
);

CREATE TABLE markers_info (
  id SERIAL PRIMARY KEY NOT NULL,
  location_name VARCHAR(255) NOT NULL,
  info TEXT NOT NULL,
  img_link VARCHAR(255)
);

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR(255) NOT NULL,
  north DECIMAL NOT NULL,
  south DECIMAL NOT NULL,
  east DECIMAL NOT NULL,
  west DECIMAL NOT NULL,
  zoom INTEGER NOT NULL,
  center_lat DECIMAL NOT NULL,
  center_lng DECIMAL NOT NULL
);

CREATE TABLE markers (
  id SERIAL PRIMARY KEY NOT NULL,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE,
  lat DECIMAL NOT NULL,
  lng DECIMAL NOT NULL,
  marker_info_id INTEGER REFERENCES markers_info(id) ON DELETE CASCADE,
  icon_id INTEGER REFERENCES icons(id) ON DELETE CASCADE
);

CREATE TABLE favorites (
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  map_id INTEGER REFERENCES maps(id) ON DELETE CASCADE
);